#!/bin/bash

set -ex

echo "Checking if '/opt/slurm' is mounted ..."

echo "'/opt/slurm' IS NOT MOUNTED"
sudo mount -t nfs "${headnode_private_ip}:/opt/slurm" "/opt/slurm"
sudo mount -t nfs "${headnode_private_ip}:/home" "/home"

echo "Copying munge key ..."

sudo cp /home/ec2-user/.munge/.munge.key /etc/munge/munge.key
sudo chown munge:munge /etc/munge/munge.key

echo "Starting munge daemon ..."
sudo service munge start

echo "Adding SLURM to path ..."
sudo tee /etc/profile.d/slurm.sh >/dev/null <<'EOF'
#
# slurm.sh:
#   Setup slurm environment variables
#

PATH=$PATH:/opt/slurm/bin
MANPATH=$MANPATH:/opt/slurm/share/man
EOF

echo "Adding DNS Configuration ..."
sudo tee /etc/resolv.conf >/dev/null <<'EOF'
# Generated by NetworkManager
search ${region}.compute.internal ${cluster_name_lowercase}.pcluster
nameserver 10.0.0.2
options timeout:2 attempts:5
EOF

source /etc/profile.d/slurm.sh

echo "Done!"

